# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateNBEmisProbCpp <- function(data, scaleFactors, nstates, muBack, muPeak, size) {
    .Call('_flexPhyloHMM_updateNBEmisProbCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, nstates, muBack, muPeak, size)
}

updateNBEmisProbDTCpp <- function(data, scaleFactors, nstates, muBack, muPeak, dispPar) {
    .Call('_flexPhyloHMM_updateNBEmisProbDTCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, nstates, muBack, muPeak, dispPar)
}

updatePeakFlexMixCpp <- function(data, scaleFactors, nstates, muBack, mixPeak, weights, dispPar, sampleNormFactor) {
    .Call('_flexPhyloHMM_updatePeakFlexMixCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, nstates, muBack, mixPeak, weights, dispPar, sampleNormFactor)
}

updateTreeEmisProbCpp <- function(data, scaleFactors, treeStates, nstates, mu, size) {
    .Call('_flexPhyloHMM_updateTreeEmisProbCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, mu, size)
}

updateTreeEmisProbDTCpp <- function(data, scaleFactors, treeStates, nstates, mu, dispParams) {
    .Call('_flexPhyloHMM_updateTreeEmisProbDTCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, mu, dispParams)
}

updateTreeEmisProbDTWindowCpp <- function(data, scaleFactors, treeStates, nstates, mu, dispParams, winSize) {
    .Call('_flexPhyloHMM_updateTreeEmisProbDTWindowCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, mu, dispParams, winSize)
}

updateTreeEmisProbGMixCpp <- function(data, scaleFactors, treeStates, nstates, muBack, mixPeak, weights, dispParams) {
    .Call('_flexPhyloHMM_updateTreeEmisProbGMixCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, muBack, mixPeak, weights, dispParams)
}

updateTreeEmisProbFlexMixCpp <- function(data, scaleFactors, deletionRanges, treeStates, nstates, muBack, mixPeak, weights, sampleNormFactor, dispParams) {
    .Call('_flexPhyloHMM_updateTreeEmisProbFlexMixCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, deletionRanges, treeStates, nstates, muBack, mixPeak, weights, sampleNormFactor, dispParams)
}

