# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

absorbingStateLogProb <- function(conditionalEmisLogProb, dataLogProb, enumLogProb, absorbLogProb) {
    .Call('_flexPhyloHMM_absorbingStateLogProb', PACKAGE = 'flexPhyloHMM', conditionalEmisLogProb, dataLogProb, enumLogProb, absorbLogProb)
}

computeLeafProb <- function(data, scaleFactors, deletionRanges, muBack, mixPeak, weights, sampleNormFactor, dispParams) {
    .Call('_flexPhyloHMM_computeLeafProb', PACKAGE = 'flexPhyloHMM', data, scaleFactors, deletionRanges, muBack, mixPeak, weights, sampleNormFactor, dispParams)
}

#' Vector logSumExp
#' 
#' This function computes the sum(e^x) of a vector x without leaving log space
#'
#' @param x A numeric vector
#' @export
logSumExp <- function(x) {
    .Call('_flexPhyloHMM_logSumExp', PACKAGE = 'flexPhyloHMM', x)
}

#' Vector logSumExpHP
#' 
#' This function computes the sum(e^x) of a vector x without leaving log space in high precision using an iterative calculation
#'
#' @param x A numeric vector
#' @export
logSumExpHP <- function(x) {
    .Call('_flexPhyloHMM_logSumExpHP', PACKAGE = 'flexPhyloHMM', x)
}

#' Vector logMinusExp
#' 
#' This function computes the  e^a-sum(e^x) of a scalar 'a' and vector 'x' without leaving log space
#'
#' @param a A scalar
#' @param x A numeric vector
#' @export
logMinusExp <- function(x, y) {
    .Call('_flexPhyloHMM_logMinusExp', PACKAGE = 'flexPhyloHMM', x, y)
}

updateNBEmisProbCpp <- function(data, scaleFactors, nstates, muBack, muPeak, size) {
    .Call('_flexPhyloHMM_updateNBEmisProbCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, nstates, muBack, muPeak, size)
}

updateNBEmisProbDTCpp <- function(data, scaleFactors, nstates, muBack, muPeak, dispPar) {
    .Call('_flexPhyloHMM_updateNBEmisProbDTCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, nstates, muBack, muPeak, dispPar)
}

updatePeakFlexMixCpp <- function(data, scaleFactors, nstates, muBack, mixPeak, weights, dispPar, sampleNormFactor) {
    .Call('_flexPhyloHMM_updatePeakFlexMixCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, nstates, muBack, mixPeak, weights, dispPar, sampleNormFactor)
}

updateTreeEmisProbCpp <- function(data, scaleFactors, treeStates, nstates, mu, size) {
    .Call('_flexPhyloHMM_updateTreeEmisProbCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, mu, size)
}

updateTreeEmisProbDTCpp <- function(data, scaleFactors, treeStates, nstates, mu, dispParams) {
    .Call('_flexPhyloHMM_updateTreeEmisProbDTCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, mu, dispParams)
}

updateTreeEmisProbDTWindowCpp <- function(data, scaleFactors, treeStates, nstates, mu, dispParams, winSize) {
    .Call('_flexPhyloHMM_updateTreeEmisProbDTWindowCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, mu, dispParams, winSize)
}

updateTreeEmisProbGMixCpp <- function(data, scaleFactors, treeStates, nstates, muBack, mixPeak, weights, dispParams) {
    .Call('_flexPhyloHMM_updateTreeEmisProbGMixCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, treeStates, nstates, muBack, mixPeak, weights, dispParams)
}

updateTreeEmisProbFlexMixCpp <- function(data, scaleFactors, deletionRanges, treeStates, nstates, muBack, mixPeak, weights, sampleNormFactor, dispParams) {
    .Call('_flexPhyloHMM_updateTreeEmisProbFlexMixCpp', PACKAGE = 'flexPhyloHMM', data, scaleFactors, deletionRanges, treeStates, nstates, muBack, mixPeak, weights, sampleNormFactor, dispParams)
}

updateTreeEnumeratedStates <- function(leafProbs, treeStates, nstates, absorbingState) {
    .Call('_flexPhyloHMM_updateTreeEnumeratedStates', PACKAGE = 'flexPhyloHMM', leafProbs, treeStates, nstates, absorbingState)
}

treeLL <- function(leafProb, qConcat, traversal, tips, logBaseFreq) {
    .Call('_flexPhyloHMM_treeLL', PACKAGE = 'flexPhyloHMM', leafProb, qConcat, traversal, tips, logBaseFreq)
}

